FROM node:alpine

ENV NODE_ENV development

WORKDIR /app

COPY ./package*.json ./

RUN npm install --silent

RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . ./

EXPOSE 3000

USER node

CMD ["npm", "start"]