version: '3.8'
services:
  reactapp:
    container_name: rv-client-dev
    image: rv-client-dev
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
  expressjs:
    container_name: rv-app
    build:
      context: ./
    env_file:
      - ./.env
    ports:
      - 8000:8000
  mongodb:
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    container_name: mongodb
    ports:
      - 27017:27017
    env_file:
      - ./.env
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.env