export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOADING_USERROOM = "LOADING_USERROOM";
export const LOADING_MESSAGESROOM = "LOADING_MESSAGESROOM";
export const SET_LEAVEROOM = "SET_LEAVEROOM";
export const CLEAR_USERSROOM = "CLEAR_USERSROOM";
export const CLEAR_MESSAGESROOM = "CLEAR_MESSAGESROOM";

